Home page
alinarub/dog-app pull request #16
Opened 2023-10-27 11:04 UTC by alinarub

2023-10-27 13:32 UTC, FelineHuhn requested changes
Well done 🙌 I left you a few suggestions for code improvement. Also your vercel deployment is currently failing, which you still need to fix. 

Keep up the good work 🚀

2023-10-27 13:32 UTC, FelineHuhn commented on components/Headline.js
> +const StyledH1 = styled.div`
```suggestion
const StyledH1 = styled.h1`
```
I take from your naming that this should be an "h1" or? Nevertheless, I would recommend you a more descriptive naming here, e.g. like `StyledHeadline` and the wrapping `div` could be named `StyledHeadlineWrapper`.

2023-10-27 13:32 UTC, FelineHuhn commented on components/Headline.js
> +      <StyledH1>{name}</StyledH1>
```suggestion
export default function Headline({ children }) {
  return (
    <StyledHeadline>
      <StyledH1>{children}</StyledH1>
```
I recommend you to use the children prop here. The children prop in React allows you to pass and render content or components inside another component. This approach provides more flexibility because you can include any JSX content within the Headline component, making it suitable for various use cases.

2023-10-27 13:32 UTC, FelineHuhn commented on pages/index.js
> +      <Headline name="Find your dog" />
```suggestion
      <Headline>Find your dog</Headline>
```
This is the adjustment due to the recommendation in the `Headline` component.

2023-10-27 13:32 UTC, FelineHuhn commented on components/LinkButton.js
> +      {name}
```suggestion
export default function LinkButton({ href, children, fullWidth }) {
  return (
    <StyledLink fullwidth={fullwidth} href={href}>
      {children}
```
Same explanation as for the `Headline` component

2023-10-27 13:32 UTC, FelineHuhn commented on pages/index.js
> +      <LinkButton fullwidth={true} href="/quiz-page" name="Start the quiz!" />
```suggestion
      <LinkButton fullwidth={true} href="/quiz-page">Start the quiz!</LinkButton>
```
This is the adjustment due to the recommendation in the `LinkButton` component.

2023-10-27 13:32 UTC, FelineHuhn commented on components/ImageTextModule.js
> +`;
Do you really need that styled component `StyledImage` here, since you already provide the `width` and `height` properties in the `Image` component itself, or?

2023-10-28 09:50 UTC, gregorsart commented
Thank you Feline, we changed the code according to your feedback. Especially the `children` prop we almost forgot.
We will push the changes in a sec.

2023-10-30 10:43 UTC, moonwave99 commented on pages/quiz-page/index.js
>      <div>
ditto

2023-10-30 10:43 UTC, moonwave99 commented on pages/quiz-results/index.js
> +      <ImageTextModule showimage={true}>
`<ImageTextModule showImage>` is enough (and use `camelCase` for props) ^^

2023-10-30 10:43 UTC, moonwave99 commented on pages/quiz-results/index.js
>          })}
Consider implicit return statement and destructuring:

```js
{
  sortedAssignedPoints.map(({ name, points }) => (
    <li key={name}>
      {name} <span>{points}</span>
    </li>
  ))
}
```

2023-10-30 13:36 UTC, moonwave99 approved these changes

2023-11-01 08:58 UTC, merged