Detail page
alinarub/dog-app pull request #19
Opened 2023-11-06 10:57 UTC by alinarub

2023-11-06 13:07 UTC, NikRoe requested changes
Hi there,

very promising start!

I left you a few comments and suggestions.

Keep it up 🐶

2023-11-06 13:07 UTC, NikRoe commented on components/RatingLine.js
> +    }
How about changing this code to something like this:

```suggestion
for (let i = 1; i < 6; ++i) {
    stars.push(
      <StyledImage
        src={`${i <= +rating ? "/paw-icon-yellow.svg" : "/paw-icon-gray.svg"}`}
        alt="Icon of a paw"
        width={15}
        height={15}
        blurDataURL="data:..."
      />
    );
  }
```

2023-11-06 13:42 UTC, alinarub commented on components/MoreDogInformation.js
> +    <div>
no 😆

2023-11-06 16:32 UTC, gregorsart commented on components/RatingLine.js
> +    }
@NikRoe ty very much for all the input. The last piece of code you suggested did not work. The reason was, that we fill the array not in the`jsx` section of the .js file but above the `return()`. As a result wie came up with: 

`src={i <= +rating ? "/paw-icon-yellow.svg" : "/paw-icon-gray.svg"}`

It works.

2023-11-07 07:06 UTC, NikRoe commented on components/RatingLine.js
> +    }
Awesome that you found a solution despite my faulty suggestion 🙌 

Before the return statement you have your normal JavaScript; you can declare variables, hooks (like useState, useEffect, etc.), and other functions. This is where you prepare everything that the component will need for rendering.

For a thorough overview what can be happening in the return statement, I asked ChatGPT and got this response:

> JSX Syntax: The code within the return statement follows JSX syntax, which allows you to write HTML-like code in your JavaScript.
> 
> JavaScript Expressions: You can embed JavaScript expressions in JSX using curly braces {}. This can include variables, function calls, map operations, etc., which can dynamically generate content.
> 
> Components: You can include React components within the JSX. This can be either standard HTML elements (like div, span, input, etc.) or other custom React components that you have created.
> 
> Props and Children: Within the JSX, you can pass data to components via "props" (short for properties), and you can nest components inside one another to create a component hierarchy.
> 
> Conditional Rendering: You can use JavaScript logic to conditionally render elements. This often involves ternary operators, logical && operators, or even immediately-invoked function expressions (IIFEs) within the JSX.
> 
> Fragments: If you need to return multiple elements without adding an extra node to the DOM, you can use React Fragments, which are represented by <> and </>.
> 
> Keys in Lists: When rendering lists of elements, React requires each element to have a unique "key" prop for efficient re-rendering.

I hope this brings some clarification 🙏

2023-11-07 07:23 UTC, gregorsart commented on components/RatingLine.js
> +    }
ty ✨

2023-11-07 09:11 UTC, NikRoe requested changes
Hi there,

very well done 👏 

I left a few suggestions related to semantic HTML, which I did not notice in my first review.

Keep it up 🐩

2023-11-07 09:11 UTC, NikRoe commented on components/MoreDogInformation.js
> +    <>
no need or fragments here

2023-11-07 09:11 UTC, NikRoe commented on components/RatingLine.js
> +const StyledSection = styled.section`
an article would be better, a section should always have a heading

2023-11-07 09:11 UTC, NikRoe commented on components/LoadingSpinner.js
> +const StyledWrapper = styled.section`
an article would be better, since sections should almost always contain a heading

2023-11-07 09:22 UTC, alinarub commented on components/MoreDogInformation.js
> +    <>
oh sorry, I misunderstood it the first time

2023-11-07 09:42 UTC, NikRoe approved these changes
LGTM 👏

2023-11-07 10:54 UTC, merged