All dogs
alinarub/dog-app pull request #21
Opened 2023-11-09 12:08 UTC by AchimBartscht

Feedback appreciated.

2023-11-10 10:05 UTC, doemser requested changes

2023-11-10 10:05 UTC, doemser commented on pages/dogs/index.js
> +
```suggestion
  const { data: dogs, isLoading } = useSWR(`/api/dogs`);
```

In the context of the provided code, if the URL for fetching the dog data (/api/dogs) doesn't depend on any router parameters (like query strings or dynamic route segments), then waiting for router.isReady before making the API call is unnecessary.

The router.isReady condition is typically used in scenarios where the API endpoint or the data you're fetching depends on parameters from the URL. For example, if you're fetching details for a specific dog and the dog's ID comes from the URL (like /dogs/[id]), you'd need to wait for router.isReady to ensure that the ID parameter is available.

Also the questionmark can be removed from the api route string

2023-11-13 10:53 UTC, NikRoe approved these changes
Hi there,

nicely done.

I left only one comment: You can remove a key in your AllDogsCard.

Since it's only a tiny change, you can simply remove the key and proceed to QA without having to repost this PR.

Best regards 🐶

2023-11-13 10:53 UTC, NikRoe commented on components/AllDogsCard.js
> +    <StyledLink href={`dogs/${name}`} key={name}>
you don't need a key here.

You need it only in the very place you are mapping over an array. In this specific case you are already doing it here: `pages/dogs/index.js`

2023-11-14 10:47 UTC, merged