Faq
alinarub/dog-app pull request #25
Opened 2023-11-14 14:26 UTC by gregorsart

Feedback appreciated.

2023-11-15 13:43 UTC, NikRoe requested changes
Hi there,

very well done 🙌 🪗 

I left only 3 comments for you to take a look at that might make your code even more maintainable and readable :)

2023-11-15 13:43 UTC, NikRoe commented on components/Accordion.js
> +  const [accordionData, setAccordionData] = useState([
I would move this initial data to a different file, maybe create a lib folder where you store the faq data.

This will make this file a lot more maintainable.

2023-11-15 13:43 UTC, NikRoe commented on components/Accordion.js
> +        )}
by changing your code to this, you could save some lines:

```suggestion
        <StyledIcon
          src={id === openIndex ? "/chevron-up.svg" : "/chevron-down.svg"}
          alt={id === openIndex ? "Chevron up arrow" : "Chevron down arrow"}
          width={29}
          height={29}
          blurDataURL="data:..."
        />
```

2023-11-15 13:43 UTC, NikRoe commented on components/Accordion.js
> +        {links &&
do you need this check? 🤔

2023-11-16 08:51 UTC, gregorsart commented on components/Accordion.js
> +        {links &&
Hey Nik, ty for the improvements. We have implemented them already. 🐶

2023-11-16 10:25 UTC, JessicaLoers requested changes
**Hello @gregorsart** 
Very well done. 🚀

I stumbled across a part that I'd like you to take another look at. 

_If the accordion should only work with predefined items and not add new ones dynamically, you can remove the second return statement._

2023-11-16 10:25 UTC, JessicaLoers commented on components/Accordion.js
> +  }
This seems to be a redundant case. If `id` is not found, should it be added? 🤔 
_Let' break it down._

`return [...accordionItems, { id, isOpen: false }];`

- This return runs of no  item with the given id was found (info is undefined or null).
- It returns a new array that includes all existing items in accordionItems plus a new object with the specified id and isOpen set to false.

➡️ _Your accordion work with predefined set of items (as provided initially by faqData). 
Adding a new item dynamically when an id is not found in accordionItems might be unnecessary or unintended, unless there's a specific reason or functionality in your application that requires this behavior 🤷‍♀️._

2023-11-16 14:20 UTC, gregorsart commented on components/Accordion.js
> +  }
Hi @JessicaLoers, ty for your detailed answer. You are completely right.

The reason behind it: We took the code from another example and we simply forgot to remove the case / code you mentioned.

In the other example (where we took the code from), the Array was empty in the beginning and should thus add items that weren't encountered before.

In our case -- as you already mentioned -- we have predefined items / objects, that are already inside the array. We only need to alter the` isOpen` key.

We will remove this unnecessary code tomorrow.

Greetings and ty again.

2023-11-17 10:40 UTC, Julia-Pickel commented
Hey @gregorsart @alinarub! 🙌

Very nice app and progress so far! 🧞‍♂️🧞‍♀️ 
As you changed all previous recommendations there's nothing to add.
Only one curious question below :)

Looking forward to seeing your next steps 🐶

2023-11-17 11:03 UTC, Julia-Pickel approved these changes

2023-11-17 11:06 UTC, alinarub commented on components/Accordion.js
> +        />
Thanks for your feedback! Do you mean we should use `const StyledIcon.svg` instead of `(Image)`?

2023-11-20 08:12 UTC, alinarub commented on components/Accordion.js
> +        />
@Julia-Pickel since we're assuming it's okay the way it is, we'll merge now, maybe you didn't see the comment :)

2023-11-20 08:12 UTC, merged