Progress bar
alinarub/dog-app pull request #32
Opened 2023-11-24 10:16 UTC by AchimBartscht

2023-11-24 11:02 UTC, doemser requested changes
I think this looks really beautiful. 😍 

You should make the progress bar depending on the actual questions length instead of harcoding the steps.

2023-11-24 11:02 UTC, doemser commented on components/ProgressBar.js
> +          <StyledProgressListItem key={i}>
never use the index as a key in react, also never abbreviate the index with `i`

2023-11-24 13:39 UTC, doemser requested changes

2023-11-24 13:39 UTC, doemser commented on components/ProgressBar.js
> +              {index + 1}
you could just pass all the questions, then go to use: `questions.length` instead of `questionsDataLength` 

this is approach for the key is unfortunately not better, essentially this eliminates any advantage react can bring us. Passing all the questions, allows you to use the question.id instead

2023-11-24 13:41 UTC, doemser commented on components/ProgressBar.js
> +            <StyledPoints $step={step} $current={index}>
```suggestion
        {questions.map((question, index) => (
          <StyledProgressListItem key={question.id}>
            <StyledPoints $step={step} $current={index}>
```

just like this

2023-11-24 13:46 UTC, Roland-Hufnagel requested changes
Hi. Please look once more at the comments. Thanks.

2023-11-24 13:46 UTC, Roland-Hufnagel commented on components/ProgressBar.js
> +  width: ${({ step }) => step * 16.667}%;
This is still hardcoded for  7 questions.

2023-11-24 14:10 UTC, doemser commented
@alinarub You can not just commit my changes, as they are not verified at all. In this case you need to pass the questions first etc. This was just a hint to guide you, not a complete integration of what I meant.

2023-11-24 14:14 UTC, alinarub commented
@doemser Sorry, yes I saw, I am working on it right now.

2023-11-27 07:13 UTC, onemanwenttomow approved these changes
🎉 LGTM

2023-11-27 09:03 UTC, merged