Results page redesign
alinarub/dog-app pull request #39
Opened 2023-12-01 09:43 UTC by alinarub

2023-12-01 11:11 UTC, Roland-Hufnagel commented on components/Header.js
> +  grid-template-columns: 1fr 10rem 1fr;
You can keep this solution if it fits for you. I only want to remind you: 
``display: flex`` is perfect for one-dimensional layout (like you have)
``display: grid`` is perfect for two-dimensional layout

2023-12-01 11:19 UTC, Roland-Hufnagel commented on components/Navigation.js
>  const StyledHeader = styled.nav`
Why do you have a ``nav`` inside your ``nav``?
And why do you name the inside nav ``StyledHeader``?
Here is something going wrong.

2023-12-02 08:43 UTC, gregorsart commented
Hi Roland, these are all good improvements and we will look into them on monday.
Ty for pointing them out.

2023-12-04 11:16 UTC, Roland-Hufnagel requested changes
Hi team. Thanks for refactoring. The structure of your code is still not perfect (but who is?). So I want you to look at it again. Decide for your own if you want to improve it or not - but if not, please leave a short comment. 

In your Header components there are still some points to improve. You can decide on you own. Since it is a ``Header`` component, I would expect to become a ``header`` - not a ``section``. Also it would be good practice to render your ``Navigation`` component conditionally.

2023-12-05 09:58 UTC, AchimBartscht commented
> Hi team. Thanks for refactoring. The structure of your code is still not perfect (but who is?). So I want you to look at it again. Decide for your own if you want to improve it or not - but if not, please leave a short comment.
> 
> In your Header components there are still some points to improve. You can decide on you own. Since it is a `Header` component, I would expect to become a `header` - not a `section`. Also it would be good practice to render your `Navigation` component conditionally.

Hi Roland, thank you for your thorough review. We appreciate your efforts. In this case, we didn't render the navigation component conditionally because we wanted a controlled `fade out` animation. With `&&` it visually behaves very abruptly. We tried a `time out` function with `&&`  but it didn't work properly.

2023-12-05 10:06 UTC, AchimBartscht commented on components/Headline.js
> +const StyledH1 = styled.h2`
Your are right. We changed the name. We'll keep the component because we might want to expand on it in the future.

2023-12-05 10:31 UTC, AchimBartscht commented on components/Navigation.js
>          <Logo handleNavigation={handleNavigation} />
We want the navigation to close if you click on the logo in the top left corner. That's why we passed the `handleNavigation` function to the logo component. 

Without this functionality we ran into the following issue: When the navigation is open and you click the logo in the top left, you navigate to the `home` page but the navigation stays open. That's why we extended the logo component.

2023-12-05 13:33 UTC, onemanwenttomow approved these changes
🎉 Nice work team. Please consider this approved but with a couple of minor suggestions.

2023-12-05 13:33 UTC, onemanwenttomow commented on pages/quiz-results/index.js
> +      </StyledList>
Is the goal here to only show the first 5 dogs from the `dogs` array?

It might make sense to [slice](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/slice) the data first. 

e.g.

``` js
dogs.slice(0, 5).map((dog) => <ResultsDogsCard dog={dog} key={dog.name} />);
```

2023-12-05 13:33 UTC, onemanwenttomow commented on pages/quiz-results/index.js
> +import Confetti from "react-confetti";
There is no set order that our imports need to be in. React leaves that decision up to us. 

But in terms of readability it might make sense to group things together. You could even establish a convention within your app so that you always follow the same process. i.e. 
* React Hooks
* Next packages
* Other packages
* Components
* Styles

``` js
import { useRouter } from "next/router";
import Link from "next/link";
import useSWR from "swr";
import Confetti from "react-confetti";
import LoadingSpinner from "@/components/LoadingSpinner";
import ResultsDogsCard from "@/components/ResultsDogsCard";
import styled from "styled-components";
```

2023-12-05 14:29 UTC, alinarub commented on pages/quiz-results/index.js
> +import Confetti from "react-confetti";
That's true, I tidied it up a bit.

2023-12-06 09:18 UTC, merged