add and style favorites page
alinarub/dog-app pull request #40
Opened 2023-12-04 10:30 UTC by gregorsart

2023-12-04 15:05 UTC, Roland-Hufnagel requested changes
Hi. Again this cool dog-app. I really like it. 
I left some comments. Please have a look at them. 
In your US is a description wireframe with a list of dogs with filled hearts in the overview. I cannot see this in the implementation. This may lead to problems in QA (but that's not my part).

2023-12-05 09:11 UTC, AchimBartscht commented on pages/dogs/[name].js
> +    }
Hi Roland, thank you for your improvement. Especially the `.includes` method is something we completely forgot about. However, for now we want to keep our solution.

2023-12-05 12:11 UTC, alinarub commented on pages/favorite-dogs/index.js
Hi Julia, thank you for reviewing! 😊 We didn't add `Favorites` on the navigation menu because we built this on an older branch that still needed refactoring, we'll add it later. You can see view the page by adding `/favorite-dogs` to the url.

2023-12-05 12:30 UTC, Julia-Pickel commented on pages/favorite-dogs/index.js
Hi @alinarub ! 
Ok, I see... thanks for the info and the link!
So, then please implement this as soon as your other branch is ready to merge. 

I will approve the code but leave a thought on your `FavoritedDogsCard`.

Keep it up ✌️

2023-12-05 12:37 UTC, Julia-Pickel commented on components/FavoritedDogsCard.js
> +  justify-content: center;
I don't think these styles are needed here.
Since you have the _display_ set to _flex_, it should work anyway.

2023-12-05 13:12 UTC, Julia-Pickel approved these changes

2023-12-06 09:17 UTC, merged