Random dog
alinarub/dog-app pull request #44
Opened 2023-12-13 10:29 UTC by AchimBartscht

2023-12-13 12:12 UTC, ThomasKirst requested changes
Hi Achim 👋

Looks all good, I just left you two minor comments.

For now, I would say the solution is fine, but for the future I would reconsider the following:
- you´re loading more than 200 dogs from your API 😅
- in your client code you grab a random dog from the list
- this could be done on the server side already where you return only one random dog to the browser in order to save some bandwidth and waiting time for the user

Also, nice design 👍

– Thomas

2023-12-13 12:12 UTC, ThomasKirst commented on pages/index.js
> +        <div>
The `div` tag might not be needed here – or is it related to the `figure` animation?

2023-12-13 12:12 UTC, ThomasKirst commented on pages/index.js
> +    }
Please check the format here.

2023-12-14 07:28 UTC, gregorsart commented on pages/index.js
> +        <div>
I think we need the extra div tag, but we will try it out without the `div` tag and when it still works we will remove it.

2023-12-14 08:26 UTC, alinarub commented on pages/index.js
> +        <div>
It works without the `div`, you're right :)

2023-12-14 08:31 UTC, alinarub commented
> Hi Achim 👋
> 
> Looks all good, I just left you two minor comments.
> 
> For now, I would say the solution is fine, but for the future I would reconsider the following:
> 
> * you´re loading more than 200 dogs from your API 😅
> * in your client code you grab a random dog from the list
> * this could be done on the server side already where you return only one random dog to the browser in order to save some bandwidth and waiting time for the user
> 
> Also, nice design 👍
> 
> – Thomas

You're right but we're now disconnected from the API, we pulled all the data to our lib folder. Now via backend route we get all the dogs on the server and send it to the frontend. Of course we could do the calculation in the backend and then send the random dog to the frontend. But we're in the last two days of our bootcamp now, so we want to focus on implementing dark mode first. :)

2023-12-14 10:40 UTC, NikRoe approved these changes
LGTM 🐕

2023-12-15 08:49 UTC, merged