Dark mode
alinarub/dog-app pull request #45
Opened 2023-12-15 10:18 UTC by gregorsart

Last PR for the app maybe 💯 

If someone has an idea on how to change the color of the `ImageTextModule` depending on two things:

1.  The passed react props (should there be a change of color yes or no)
2. The active theme mode (dark / light) we get via react context api

And last but not least we "invented" a working solution for the `CreateGlobalStyles` and implemented it in app.js in `line 23`

`{themeMode === "light" ? <GlobalStyle /> : <DarkModeStyles />}`

We are not sure if this is best practice (but it works)

2023-12-15 14:58 UTC, ThomasKirst requested changes
Hi Gregor,

looks pretty amazing to me, well done!

About the question in your PR description: I´m not sure what you want to achieve – maybe open a question on the discussion with a bit more details / context?

About your "invention" of having a separate configuration of Global Styles for the dark mode: I like your solution and I would not overcomplicate it. I left you there a tiny comment on how to improve it a little, but overall it´s a smart solution. You basically just want to override the CSS variables on the given context, that´s great!

There are other ways of "overriding" styles as described [in this article](https://dev.to/britotiagos/using-props-on-styled-component-and-nextjs-51lk), for instance. Then you would have to pass the theme prop to GlobalStyles, but I don´t think that´s necessary.

I hope this helps.
– Thomas

2023-12-15 14:58 UTC, ThomasKirst commented on components/DarkmodeButton.js
> +    </>
No fragment needed here:

```suggestion
      <ToggleContainer>
        <ToggleBorder>
          <Toggle $isToggled={isToggled}>
            <StyledInput
              type="checkbox"
              value=""
              checked={themeMode === "dark"}
              className=""
              onChange={onChangeToDark}
            />
          </Toggle>
        </ToggleBorder>
      </ToggleContainer>
```

2023-12-15 14:58 UTC, ThomasKirst commented on styles.js
> +
Please prettify (remove double empty lines).

2023-12-15 14:58 UTC, ThomasKirst commented on styles.js
> +  }
The styles which are shared both by light and dark mode could be written in another variable and then included here as `${sharedGlobalStyles}` or similar.

2023-12-15 14:58 UTC, ThomasKirst commented on components/DarkmodeButton.js
> +            />
```suggestion
            <StyledInput
              type="checkbox"
              checked={themeMode === "dark"}
              onChange={onChangeToDark}
            />
```

2023-12-15 14:58 UTC, ThomasKirst commented on components/Header.js
> +              placeholder="blur" // Optional blur-up while loading
Does this serve any purpose now or can it be removed?

2023-12-15 14:58 UTC, ThomasKirst commented on pages/_app.js
> +    defaultValue: ["light"],
You initially set the `defaultValue` to an array with one item `light`, but I guess you simply want to store the string `light` here.

2023-12-18 07:39 UTC, NikRoe approved these changes
LGTM 🙌

2023-12-18 08:47 UTC, merged