Api test
alinarub/dog-app pull request #6
Opened 2023-10-17 09:03 UTC by alinarub

2023-10-17 10:02 UTC, willywdev commented on pages/index.js
> +  console.log("assignedPoints---", assignedPoints);
```suggestion
```

Remove console.logs from Production Builds

2023-10-17 10:06 UTC, willywdev requested changes
Hey this looks very promising!
I would suggest to remove all Console.Logs from Production Builds.

Also you could try to clean up some commented Code Brackets, although I don't know how important they are as of now.

2023-10-17 10:06 UTC, willywdev commented on pages/index.js
> +  console.log("assignedPoints---", assignedPoints);
```suggestion
```
Remove console.logs from Production Builds.

2023-10-17 10:06 UTC, willywdev commented on pages/index.js
> +    console.log("one point added");
```suggestion
```

2023-10-17 10:06 UTC, willywdev commented on pages/index.js
> +        console.log("barking");
```suggestion
```

2023-10-17 10:06 UTC, willywdev commented on pages/index.js
> +        console.log("energy");
```suggestion
```

2023-10-17 10:06 UTC, willywdev commented on pages/index.js
> +        console.log("trainability");
```suggestion
```

2023-10-17 10:06 UTC, willywdev commented on pages/index.js
> +    console.log("answerValues---", answerValues);
```suggestion
```

2023-10-17 10:56 UTC, alinarub commented
Thanks for the review! We removed all console logs. For the commented code brackets, we want to keep them for now because they help us for future coding.

2023-10-18 08:16 UTC, NikRoe approved these changes
Hi there,

this looks good to me!

I left only one comment for the future ;)

Best regards 👋

2023-10-18 08:16 UTC, NikRoe commented on pages/index.js
At a point in the very near future, you should think about moving `dummyDogs`, `assignPointsToDogs` and `calculateAssignedPoints` to a different file.
You could have a utils folder where you store those helper functions. 

This will make your `pages/index.js` a lot smaller and thus more readable

2023-10-19 08:02 UTC, merged